### ISSUE TITLE
Question: How to "Unload" the Mod, for 1.20.4

### ISSUE THREAD

**Issue by LunaFabula** [theendercore/BiomeTagVillagers#1]
I'm playing on 1.20.4 (still), I've tried the mod and I don't want to keep the changes that are made - I want the villagers to retain the biome I found them in.... How can I get rid of the changes this mod does?

**Comment by theendercore** [comment]
Um, I don't think I understand your problem. All the mod does is go to where vanilla says.  
> I'm making a new villager, what profession should it be?

And it just changed the code to use tags instead of biome names. The mod doesn't actually change the biomes, though. The custom tags contain the same biome as vanilla, without the mod. So unless you have added a data pack that does change this, then you can just remove the mod, and you should be good. 

But if you have made a data pack then the mod can't revert villager types since that's determined on their creation.
